### ISSUE TITLE
Division by zero in index.php

### ISSUE THREAD

**Issue by Zeratyl06** [g613/asterisk-cdr-viewer#38]
Hi! I often get this message in php log:

"PHP message: PHP Warning:  Division by zero in asterisk-cdr-viewer/index.php on line 757"

**Comment by g613** [comment]
should be fixed in 
https://github.com/g613/asterisk-cdr-viewer/commit/343b06fa873bcbaf07be185ba41c2623c811772f

**Comment by Zeratyl06** [comment]
Thank you!
